### PR TITLE
OQS encoding as per IETF116

### PR DESCRIPTION
**Pull request by baentsch**
Do not merge until tested!

This PR deposits artefacts using the IETF115 OIDs (except new Falcon OIDs in latest commit) and "classic" OQS key encoding format (as used at IETF115) but using the latest (IETF116) oqs-provider (incl. most current Falcon implementation).

Data re-generation can be done, e.g., by running within the "providers/oqs" directory

    docker run -v `pwd`:/ietf -t openquantumsafe/oqs-ossl3:ietf116-hotfix sh -c "apk add bash && cd /ietf && ./gen.sh"

### CODE REVIEW

**Comment by baentsch** [comment]
@ounsworth FYI/testing

**Comment by ounsworth** [comment]
@baentsch You have changed:
```
    runandlog ${dir} falcon512 1.3.9999.3.1
   runandlog ${dir} falcon1024 1.3.9999.3.4
```
to
```
   runandlog ${dir} falcon512 1.3.9999.3.6
   runandlog ${dir} falcon1024 1.3.9999.3.9
```

this change should also be reflected in [oid_mapping.md](https://github.com/IETF-Hackathon/pqc-certificates/blob/master/docs/oid_mapping.md) ... I'll do that right now.

**Comment by johngray-dev** [comment]
Looks good.  Thanks for putting this together Michael and Mike!  We had a big discussion on NCCoE about this pull request as well.

**Review by johngray-dev — APPROVED** [review]
Looks good.  Thanks Michael!

**Review by ounsworth — APPROVED** [review]

**Pull request merged**
