### PR TITLE
update using QSC encoding RFCv00 as of IETF116

### PR DESCRIPTION
**Pull request by baentsch**
Do not merge until tested!

This PR deposits artefacts using the IETF115 OIDs (except new Falcon OIDs in latest commit) but uses [the QSC-encoding method](https://datatracker.ietf.org/doc/draft-uni-qsckeys/00/) and the latest (IETF116) oqs-provider (incl. most current Falcon implementation).

Data re-generation can be done, e.g., by running within the "providers/oqs" directory

    docker run -v `pwd`:/ietf -t openquantumsafe/oqs-ossl3:ietf116-hotfix sh -c "apk add bash && cd /ietf && ./gen.sh"

### CODE REVIEW

**Comment by baentsch** [comment]
@ounsworth FYI/testing

**Comment by baentsch** [comment]
@ralienpp FYI as discussed yesterday. See [here](https://github.com/open-quantum-safe/oqs-provider/blob/main/ALGORITHMS.md#key-encodings) for how to activate this encoding. I have no clue whether anyone else uses this. Asking   for feedback by @ounsworth @johngray-dev . Tagging @xvzcf in case of questions in April (vacations starting now :).

**Comment by ounsworth** [comment]
Here is a discussion on the NIST pqc list about encodings: NIST said:

> Our (NIST’s) current plan is to encode signatures, ciphertexts, and public keys as byte strings. I think this is closest to (A) from your list.
> -Ray Perlner

That means these ASN.1 based encoding will most likely be obsoleted.

https://groups.google.com/a/list.nist.gov/g/pqc-forum/c/SM7KcTE7Cpo

**Comment by mouse07410** [comment]
> Here is a discussion on the NIST pqc list about encodings: NIST said:
> 
> > Our (NIST’s) current plan is to encode signatures, ciphertexts, and public keys as byte strings. I think this is closest to (A) from your list.
> > -Ray Perlner
> 
> That means these ASN.1 based encoding will most likely be obsoleted.
> 
> https://groups.google.com/a/list.nist.gov/g/pqc-forum/c/SM7KcTE7Cpo

And I, for one, am _very_ happy about this.

**Comment by baentsch** [comment]
Thanks for the feedback: Very helpful to decide on good features for `oqsprovider` ([now also removed as default build feature](https://github.com/open-quantum-safe/oqs-provider/blob/12a6418f1b6c532a88bccd2d6dac5c10a2460af4/CMakeLists.txt#L20)) and what to focus on.

**Pull request closed without merging**
