### PR TITLE
first batch of BC samples

### PR DESCRIPTION
**Pull request by dghgit**
I've generated some samples for Falcon and Dilithium as well as had a go at verifying the published ones. I'm ignoring SPHINCS+ for the moment.

I got the following errors for entrust/artifacts.zip:

Entry artifacts/1.3.9999.3.1/ca/ca.csr failed to verify
Entry artifacts/1.3.9999.3.1/ee/ee.csr failed to verify
Entry artifacts/1.3.9999.3.1/ta/ta.csr failed to verify
Entry artifacts/1.3.9999.3.1/ta/ta.der failed to verify: java.security.SignatureException: certificate does not verify with supplied key
Entry artifacts/1.3.9999.3.1/ca/ca.der failed to verify: java.security.SignatureException: certificate does not verify with supplied key
Entry artifacts/1.3.9999.3.1/ee/ee.der failed to verify: java.security.SignatureException: certificate does not verify with supplied key
Entry artifacts/1.3.9999.3.4/ca/ca.csr failed to verify
Entry artifacts/1.3.9999.3.4/ee/ee.csr failed to verify
Entry artifacts/1.3.9999.3.4/ta/ta.csr failed to verify
Entry artifacts/1.3.9999.3.4/ta/ta.der failed to verify: java.security.SignatureException: certificate does not verify with supplied key
Entry artifacts/1.3.9999.3.4/ca/ca.der failed to verify: java.security.SignatureException: certificate does not verify with supplied key
Entry artifacts/1.3.9999.3.4/ee/ee.der failed to verify: java.security.SignatureException: certificate does not verify with supplied key

I'm wondering if we've both implemented the same version of Falcon!

I can't parse the what's in kris/artifacts.zip - it appears that the basicConstraints extension is in the ta certificates twice.

carl_redhound/artifacts.zip - failures in Falcon as well.

corey_snakefoot/artifacts.zip - Falcon again fails, Dilithium looks like it's passing.

oqs/openssl111/artifacts.zip - Falcon again.

oqs/oqsprovider/artifacts.zip - Falcon again.

Okay, I'm convinced. I'd be curious to know if anyone can verify what we're producing with Falcon. I'll investigate this further tomorrow,

### CODE REVIEW

**Comment by dghgit** [comment]
Okay, I had an inspiration. I've found the difference we have a byte which is set to (0x20 + LOGN) separating the nonce and the actual encoded signature, this is in addition to the (0x30 + LOGN) at the start. The (0x20 + LOGN) is actually in the submission test vectors. This might be a dumb question, I'll sit down and reread the specs tomorrow, but have we missed a memo somewhere?

**Comment by carl-wallace** [comment]
I get validity period errors for these. Here's a sample from 1.3.6.1.4.1.2.267.11.4.4/ee/ee.der.

  88   30:     SEQUENCE {
  90   13:       UTCTime 07/11/2022 05:21:48 GMT
 105   13:       UTCTime 07/11/2021 05:22:48 GMT
         :       }

**Comment by kriskwiatkowski** [comment]
@dghgit The 0x20 vs 0x30 is super confusing, I had similar problem. So, from what I understand:
* 0x20 - you use this when your signature contains a message. Signatures in KAT vectors contain a message
* 0x30 - you use this when your signature DOES NOT contain a message (detached signature)

Obviously for X.509 certs, what you want is ``0x30 + N``. 

For more details see (spec)[https://falcon-sign.info/falcon.pdf]. Namely, point ``3.11.3`` says that header byte is of form "0cc1nnnn". Then point ``3.11.6`` says that header byte is of form ``0010nnnn``. Note 4th bit from left is different.

Now:
* The latter encoding of signature is the one used by KATs (because that's required by NIST API)
* PQClean uses former encoding with ``cc=01``, because PQClean is compressed encoding (signature sizes are variable)
* Mine encoding of signatures is fixed size, because I've found out that variable size Falcon signatures are problematic in the long run. With some work I should be able also to verify other signatures. With some work on PQClean, I should be able to make it verify also my fixed-size signatures (that's my next thing to do)

**Comment by dghgit** [comment]
Ah... thanks @kriskwiatkowski that actually makes sense... appreciate the tip. @carl-wallace you know what they say about Oz, 11 hours ahead, 1 year behind... thanks for picking it up, I've updated the pull request so the dates and the tool is correct. I should be able to get the Falcon signatures sorted out tomorrow - I'll just need to fix the KAT processing first.

**Review by baentsch — COMMENTED** [review]
Suggest to also add row and column of results to results matrix https://github.com/IETF-Hackathon/pqc-certificates/blob/master/compat_matrix.md

**Comment by carl-wallace** [comment]
That fixed the validity issue but now the issue is missing basiconstraints, key usage etc in the CA cert.

**Comment by dghgit** [comment]
Okay, so I've fixed Falcon, results looking a lot better. Have added a row to the matrix as well. Falcon change will appear in 173b07 which will be up in https://www.bouncycastle.org/betas shortly.

**Comment by carl-wallace** [comment]
@dghgit They all verify for me now. Thanks.

**Comment by kriskwiatkowski** [comment]
Same here, they all verify correctly for me. Thanks.

**Comment by dghgit** [comment]
sorry, I based it off the entrust archive - is .der actually supposed to mean DER in this case?

**Comment by dghgit** [comment]
For anyone interested the new BC beta with the correct Falcon encoding is now up on https://www.bouncycastle.org/betas

**Comment by kriskwiatkowski** [comment]
@dghgit Yes. I think we said, by default we provide DER format and optionally PEMs

**Comment by opencrypto** [comment]
Worked on fixed the conflict for the compatibility matrix. Moved the bc/ directory inside the providers/ directory and added the Makefile to allow for the default targets to work (e.g., make unzip). TODO: add gen.sh and check.sh scripts to support the `make generate`, `make verify`, and `make cross_verify` targets.

**Pull request merged**
